'use client';

import { Spike } from '@/types/spike';

export function exportCSV(spikes: Spike[], filename = 'spike-export.csv') {
  const headers = ['Date', 'Time', 'Type', 'Intensity', 'Duration (seconds)', 'Notes'];

  const rows = spikes.map((s) => {
    const d = new Date(s.logged_at);
    return [
      d.toLocaleDateString('en-CA'), // YYYY-MM-DD
      d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true }),
      s.type,
      s.intensity.toString(),
      s.duration_seconds?.toString() || '',
      (s.notes || '').replace(/"/g, '""'), // Escape quotes
    ];
  });

  const csv = [
    headers.join(','),
    ...rows.map((r) => r.map((cell) => `"${cell}"`).join(',')),
  ].join('\n');

  downloadBlob(csv, filename, 'text/csv');
}

export function exportPDF(spikes: Spike[], filename = 'spike-report.html') {
  // Generate a printable HTML report that can be saved as PDF via browser print
  const total = spikes.length;
  const anxiety = spikes.filter((s) => s.type === 'anxiety').length;
  const sadness = spikes.filter((s) => s.type === 'sadness').length;
  const avgIntensity = total > 0
    ? (spikes.reduce((sum, s) => sum + s.intensity, 0) / total).toFixed(1)
    : '0';

  const rows = spikes
    .map((s) => {
      const d = new Date(s.logged_at);
      const date = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
      const time = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
      const type = s.type === 'anxiety' ? 'Anxiety' : 'Sadness';
      const duration = s.duration_seconds ? `${Math.floor(s.duration_seconds / 60)}m ${s.duration_seconds % 60}s` : '—';
      return `<tr>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd">${date}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd">${time}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd;color:${s.type === 'anxiety' ? '#7c3aed' : '#0284c7'};font-weight:600">${type}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd;text-align:center;font-weight:700">${s.intensity}/5</td>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd">${duration}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #ddd;font-size:12px;color:#666">${s.notes || ''}</td>
      </tr>`;
    })
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Spike Mood Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #333; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .stats { display: flex; gap: 24px; margin-bottom: 24px; }
    .stat { background: #f5f5f5; border-radius: 8px; padding: 16px 20px; text-align: center; }
    .stat-value { font-size: 28px; font-weight: 700; }
    .stat-label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 8px 10px; border-bottom: 2px solid #333; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; }
    .footer { margin-top: 32px; font-size: 12px; color: #aaa; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Spike Mood Report</h1>
  <div class="subtitle">Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} &mdash; ${total} entries</div>

  <div class="stats">
    <div class="stat"><div class="stat-value">${total}</div><div class="stat-label">Total Spikes</div></div>
    <div class="stat"><div class="stat-value" style="color:#7c3aed">${anxiety}</div><div class="stat-label">Anxiety</div></div>
    <div class="stat"><div class="stat-value" style="color:#0284c7">${sadness}</div><div class="stat-label">Sadness</div></div>
    <div class="stat"><div class="stat-value">${avgIntensity}</div><div class="stat-label">Avg Intensity</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Date</th><th>Time</th><th>Type</th><th style="text-align:center">Intensity</th><th>Duration</th><th>Notes</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    Generated by Spike Mood Tracker &mdash; This report is intended for clinical review.<br>
    To save as PDF: File &rarr; Print &rarr; Save as PDF
  </div>
</body>
</html>`;

  // Open in a new window for printing
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
