# VictoriaMetrics scrape config — NDN cluster monitoring
global:
  scrape_interval: 15s
  external_labels:
    cluster: ndn-swarm

scrape_configs:
  - job_name: node_exporter
    dns_sd_configs:
      - names:
          - "tasks.node_exporter"
        type: A
        port: 9100

  - job_name: postgres
    static_configs:
      - targets:
          - "postgres_exporter:9187"
        labels:
          instance: sage_mode
